/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fbf9fb",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed01b",
        "surface-container": "#efedef",
        "inverse-on-surface": "#f2f0f2",
        "primary-fixed": "#d6e3ff",
        "inverse-surface": "#303032",
        "on-primary-fixed-variant": "#39475f",
        "secondary-fixed": "#ffe083",
        "on-surface-variant": "#44474d",
        "primary-container": "#0d1c32",
        "on-background": "#1b1b1d",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#515f78",
        "secondary-fixed-dim": "#eec200",
        "danger-red": "#ef4444",
        "success-green": "#22c55e",
        "secondary": "#735c00",
        "surface-card": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#2b1701",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b9c7e4",
        "surface-bright": "#fbf9fb",
        "surface-variant": "#e4e2e4",
        "surface-container-high": "#eae7ea",
        "outline": "#75777e",
        "error": "#ba1a1a",
        "primary": "#000000",
        "outline-variant": "#c5c6cd",
        "on-tertiary-container": "#9f7d5b",
        "surface-dim": "#dbd9db",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f5f3f5",
        "tertiary-fixed": "#ffdcbd",
        "tertiary": "#000000",
        "error-container": "#ffdad6",
        "on-primary-container": "#76849f",
        "inverse-primary": "#b9c7e4",
        "on-primary-fixed": "#0d1c32",
        "surface-bg": "#f7f9fb",
        "background": "#fbf9fb",
        "on-secondary-fixed": "#231b00",
        "tertiary-container": "#2b1701",
        "on-secondary-fixed-variant": "#574500",
        "on-surface": "#1b1b1d",
        "surface-container-highest": "#e4e2e4",
        "on-tertiary-fixed-variant": "#5d4124",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#e7bf99",
        "on-secondary-container": "#6f5900"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "8px",
        "stack-lg": "32px",
        "margin-page": "24px",
        "container-padding": "24px",
        "stack-xl": "48px",
        "stack-md": "16px",
        "unit": "4px",
        "gutter-grid": "16px",
        "gutter": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "numeric-data": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "numeric-data": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms")
  ],
}
